### ISSUE TITLE
Im Canadian

### ISSUE THREAD

**Issue by BajanVlogs** [0x15f/SwiftPay-Plugin#1]
Can u let canadians use this we cant add our credit card

**Comment by 0x15f** [comment]
Stripe allows non-us users to add information. Just skip the SS box.

**Comment by BajanVlogs** [comment]
How do I do that can u show me example

**Comment by BajanVlogs** [comment]
![screenshot_20171220-091205](https://user-images.githubusercontent.com/29712167/34211075-fd64d3d6-e565-11e7-979f-bf7ad0f31e08.png)

**Comment by BajanVlogs** [comment]
![screenshot_20171220-091550](https://user-images.githubusercontent.com/29712167/34211228-767f5926-e566-11e7-9c80-5e0b7f4799a6.png)

**Comment by 0x15f** [comment]
SwiftPay's site isn't fully operational, we may be moving from Stripe to a new gateway.
