### ISSUE TITLE
Hello, would you mind helping me? What does this mean?

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [0x15f/SwiftPay-Plugin#3]
30.12 20:41:09 [Server] Server thread/DEBUG #18 /jar/pocketmine/pmmp/1.2.7-alpha10/PocketMine-MP.phar(9): include(string phar:///jar/pocketmine/pmmp/1.2.7-alpha10/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
30.12 20:41:09 [Server] Server thread/DEBUG #17 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
30.12 20:41:09 [Server] Server thread/DEBUG #16 src/pocketmine/Server(1737): pocketmine\Server->start()
30.12 20:41:09 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
30.12 20:41:09 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2274): pocketmine\Server->tick()
30.12 20:41:09 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2522): pocketmine\network\Network->processInterfaces()
30.12 20:41:09 [Server] Server thread/DEBUG #12 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
30.12 20:41:09 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/RakLibInterface(82): raklib\server\ServerHandler->handlePacket()
30.12 20:41:09 [Server] Server thread/DEBUG #10 vendor/pmmp/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 71.196.120.10:59251, raklib\protocol\EncapsulatedPacket object, integer 0)
30.12 20:41:09 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/RakLibInterface(143): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
30.12 20:41:09 [Server] Server thread/DEBUG #8 src/pocketmine/Player(2982): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
30.12 20:41:09 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
30.12 20:41:09 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/protocol/BatchPacket(118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
30.12 20:41:09 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
30.12 20:41:09 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
30.12 20:41:09 [Server] Server thread/DEBUG #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(220): pocketmine\Player->chat(string /bu)
30.12 20:41:09 [Server] Server thread/DEBUG #2 src/pocketmine/Player(2121): pocketmine\Server->dispatchCommand(pocketmine\Player object, string bu)
30.12 20:41:09 [Server] Server thread/DEBUG #1 src/pocketmine/Server(1982): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string bu)
30.12 20:41:09 [Server] Server thread/DEBUG #0 src/pocketmine/command/SimpleCommandMap(258): DuelBUHC\command\BuildUHC->execute(pocketmine\Player object, string bu, array Array())
30.12 20:41:09 [Server] Server thread/CRITICAL TypeError: "Return value of DuelBUHC\command\BuildUHC::execute() must be of the type boolean, none returned" (EXCEPTION) in "BUHCgame.phar/src/DuelBUHC/command/BuildUHC" at line 43
30.12 20:41:09 [Server] Server thread/CRITICAL Unhandled exception executing command 'bu' in buhc: Return value of DuelBUHC\command\BuildUHC::execute() must be of the type boolean, none returned

**Comment by armagadon159753** [comment]
If you read more i can see the  error cause by your BuildUHC plugin

**Comment by 0x15f** [comment]
Irrelevant to SwiftPay.
